apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: frontend  
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"




# apiVersion  kind ve  metadata 
# her k8s obje tanımında olması gereken ana
# bileşenlerdir

# kind ne olduşturmaak istiyorsaano yazılır. pod cluster vs
# apiVersion ojenin hangi apide tanımlandığı kısım kubetl aracılıgıyla bulunur
#kubectl explain pods diyince öğrenilir.

#metadata kısmı objeye özel alanlar

#spec her obje tipine göre belirlitilr . her obje için farklı