apiVersion: v1
kind: Pod
metadata: 
  name: podlife
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ['sh','-c','echo "Hello, K8s" && sleep 20']
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
          