apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

 #minikube service --url servis_Adı konutu bize bir port ve host veriyor.buna bir teminalden curl atınca
 #dış dünyadan erişilmiş gibi simüle ediyor.


 
