apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  db_server: "db.example.com"
  rumeysa: "yuk"
  site.settings: |
    color=blue
    padding:25px
---
apiVersion: v1
kind: Pod
metadata:
  name: configmappod
spec:
  containers:
  - name: configmapcontainer
    image: ozgurozturknet/k8s:blue
    env:
      - name: DB_SERVER
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: db_server
      - name: DATABASE
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: rumeysa
    volumeMounts:
      - name: config-vol
        mountPath: "/config"
        readOnly: true
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
  volumes:
    - name: config-vol
      configMap:
        name: myconfigmap