apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData: #data diye de oluşrulabilir.
  db_password: Pass1234.
  db_server:  db.example.com
  db_user: admin
# 8 farklı tipi var. Opaque bunlardan biri ve defaultu. TLS serfifikaları gibi verileri saklamak için kullanılabilir.
# kubectl get secrets ile listemele yapılır.

#elle oluşturmak için
#kubectl create secret generic mysecret2 --from-literal=db_user=rumeysa --from-literal=db_pass=test1234. 